### PR TITLE
Protobuf: Fix for C5041 for VC++ >= 15.5

### LINKED ISSUE #8978: Generates C5041 warning as of VC++ 15.5
As of VC++ 15.5, protobuf generates build warning C5041. 15.5 made static constexpr variables implicitly inline: https://docs.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements-2017?view=msvc-160#inline-variables

I have already fixed this and will be submitting the change in a PR.

**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript

**What operating system (Linux, Windows, ...) and version?**

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**

**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

### PR DESCRIPTION
**Pull request by sparist**
Introduced in 15.5: https://docs.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements-2017?view=msvc-160#inline-variables
15.5 is 1912: https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-160

fixes  #8978

### CODE REVIEW

**Comment by Eddie-cz** [comment]
@googlebot I signed it!

File: src/google/protobuf/compiler/cpp/cpp_enum.cc [hunk 1]
```diff
@@ -409,10 +409,10 @@ void EnumGenerator::GenerateMethods(int idx, io::Printer* printer) {
     std::string parent = ClassName(descriptor_->containing_type(), false);
     // Before C++17, we must define the static constants which were
     // declared in the header, to give the linker a place to put them.
-    // But pre-2015 MSVC++ insists that we not.
+    // But MSVC++ from pre-2015 to 2017 version 15.5 insists that we not.
```
Comment (acozzette) [inline src/google/protobuf/compiler/cpp/cpp_enum.cc:412]: It sounds to me like the problem exists until 2015 *and* starting from 2017 version 15.5 and later, right? I guess MSVC fixed the bug in 2015 but reintroduced it in 2017. So maybe the comment should be more like: "But MSVC++ pre-2015 and post-2017 (version 15.5+) insists that we not."

**Comment by acozzette** [comment]
@sparist Thanks for fixing this!
