### PR TITLE
Fix more issues for reference values

### LINKED ISSUE #5091: [PHP] "Given value cannot be converted to string" when setting RepeatedField value.
**What version of protobuf and what language are you using?**
Version: v3.6.1
Language: PHP 7.2 (observed in all 7-series of PHP)

**What runtime / compiler are you using (e.g., python version or gcc version)**

PHP C extension

**What did you do?**

Created an array of strings, accessed the values by reference, then assigned it to a protocol buffer value.

**What did you expect to see**

Successful assignment

**What did you see instead?**

"PHP Fatal error:  Given value cannot be converted to string."

This error does not appear to affect the protobuf pure PHP implementation. The error also does not seem to affect fields of type `string`.

A sample to reproduce this error using Cloud Firestore:

```php
<?php

use Google\Cloud\Firestore\V1beta1\BatchGetDocumentsRequest;

$documents = [
    'a', 'b', 'c'
];

function doThing(&$val) {}

// Either of these two lines cause the error. If they are removed, the error goes away.
doThing($documents[2]);
array_walk($documents, function (&$document) {});

$b = new BatchGetDocumentsRequest;
$b->setDocuments($documents);
```

### PR DESCRIPTION
**Pull request by TeBoring**
Fix #5091

### CODE REVIEW

**Comment by TeBoring** [comment]
@jdpedrie, could you take a look?

**Comment by TeBoring** [comment]
Done

File: php/tests/map_field_test.php [hunk 1]
```diff
@@ -448,6 +448,24 @@ public function testMessage() {
 
     public function testMapElementIsReference()
     {
+        // Bool elements
```
Comment (jdpedrie) [inline php/tests/map_field_test.php]: As a small note, tests like this may be easier to manage using a data provider, like this:

```php
public function mapElementIsReference()
{
    return [
        [
            [true => true],
            'setMapBoolBool'
        ], [
            [1 => 1],
            'setMapInt32Int32'
        ], [
            [1 => 1.0],
            'setMapInt32Double'
        ], [
            ['a' => 'a'],
            'setMapStringString'
        ], [
            [1 => new Sub()],
            'setMapInt32Message'
        ]
    ];
}

/**
 * @dataProvider mapElementIsReference
 */
public function testMapElementIsReference($values, $method)
{
    array_walk($values, function ($value) {});
    $m = new TestMessage();
    call_user_func($m, $method, $values);
}
```

It looks perfectly fine as is, but I often find data providers allow for more concise tests against a set of inputs.

Comment (TeBoring) [reply php/tests/map_field_test.php]: Thanks for the suggestion. I will try it next time.
