### PR TITLE
Tweak the union used for Extensions to support old generated code.

### LINKED ISSUE #7555: Incorrect source generation for GPBExtensionDescription
**What version of protobuf and what language are you using?**
Version: 3.11.2
Language:Objective-C

**What operating system (Linux, Windows, ...) and version?**
MacOS 10.15.4

**What runtime / compiler are you using (e.g., python version or gcc version)**
Xcode 11.5
coocapods 1.9.2

**What did you do?**
Steps to reproduce the behaviour:
Using the code at https://github.com/GoogleCloudPlatform/ios-docs-samples/tree/master/text-to-speech, and locking the gRPCPlugin to version 1.27.
`pod install`

**What did you expect to see**
When compiling the `annotations.proto` file, a section of generated code is:

```
+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    registry = [[GPBExtensionRegistry alloc] init];
    static GPBExtensionDescription descriptions[] = {
      {
        .defaultValue.valueMessage = nil,
        .singletonName = GPBStringifySymbol(AnnotationsRoot_HTTP),
        .extendedClass = GPBStringifySymbol(GPBMethodOptions),
        .messageOrGroupClassName = GPBStringifySymbol(HttpRule),
        .enumDescriptorFunc = NULL,
        .fieldNumber = 72295728,
        .dataType = GPBDataTypeMessage,
        .options = GPBExtensionNone,
      },
    };
    for (size_t i = 0; i < sizeof(descriptions) / sizeof(descriptions[0]); ++i) {
      GPBExtensionDescriptor *extension =
          [[GPBExtensionDescriptor alloc] initWithExtensionDescription:&descriptions[i]];
      [registry addExtension:extension];
      [self globallyRegisterExtension:extension];
      [extension release];
    }
    // None of the imports (direct or indirect) defined extensions, so no need to add
    // them to this registry.
  }
  return registry;
}
```

**What did you see instead?**
The struct does not have this signature and the code that should be generated is:
```
+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    registry = [[GPBExtensionRegistry alloc] init];
    static GPBExtensionDescription descriptions[] = {
      {
        .defaultValue.valueMessage = nil,
        .singletonName = GPBStringifySymbol(AnnotationsRoot_HTTP),
        .extendedClass = GPBStringifySymbol(GPBMethodOptions),
        .messageOrGroupClass.name = GPBStringifySymbol(HttpRule),
        .enumDescriptorFunc = NULL,
        .fieldNumber = 72295728,
        .dataType = GPBDataTypeMessage,
        .options = GPBExtensionNone,
      },
    };
    for (size_t i = 0; i < sizeof(descriptions) / sizeof(descriptions[0]); ++i) {
      GPBExtensionDescriptor *extension =
          [[GPBExtensionDescriptor alloc] initWithExtensionDescription:&descriptions[i]];
      [registry addExtension:extension];
      [self globallyRegisterExtension:extension];
      [extension release];
    }
    // None of the imports (direct or indirect) defined extensions, so no need to add
    // them to this registry.
  }
  return registry;
}
```

Note that `messageOrGroupClassName` has been turned into a union type:

The description of the struct is in `GPBDescriptor_PackagePrivate.h`:
```
// An extension
typedef struct GPBExtensionDescription {
  GPBGenericValue defaultValue;
  const char *singletonName;
  union {
    const char *name;
    Class clazz;
  } extendedClass;
  union {
    const char *name;
    Class clazz;
  } messageOrGroupClass;
  GPBEnumDescriptorFunc enumDescriptorFunc;
  int32_t fieldNumber;
  GPBDataType dataType;
  GPBExtensionOptions options;
} GPBExtensionDescription;
```

### PR DESCRIPTION
**Pull request by thomasvl**
Support the old field name as well as the union to keep the old generated code
building.

Fixes #7555

### CODE REVIEW

**Comment by thomasvl** [comment]
@dmaclach fyi.

File: objectivec/GPBDescriptor_PackagePrivate.h [hunk 1]
```diff
@@ -131,14 +131,28 @@ typedef NS_OPTIONS(uint8_t, GPBExtensionOptions) {
...
+  // initialization (https://en.cppreference.com/w/c/language/struct_initialization#Nested_initialization)
+  // old generated code with `.extendedClass = GPBStringifySymbol(Something)`
+  // still works; and the current generator can use `extendedClass.clazz`, to
+  // pass a Class reference.
   union {
     const char *name;
     Class clazz;
   } extendedClass;
+  // Before 3.12, this was `const char *messageOrGroupClassName`. In the
+  // initial 3.12 release, we moved the the `union messageOrGroupClass`, and
```
Comment (dmaclach) [inline objectivec/GPBDescriptor_PackagePrivate.h:144]: fix "the the"

"This keeps both older and newer code working"

Add a bug reference as well to find it?

Comment (thomasvl) [reply objectivec/GPBDescriptor_PackagePrivate.h]: Updated

**Comment by ashiqe26** [comment]
Patch

**Review by abhinavttyagi — COMMENTED** [review]
ok
