### PR TITLE
Fix warnings raised by clang 11

### LINKED ISSUE #8580: compile warning Clang 11 on C++
I have these warnings 

 
```
google/protobuf/compiler/cpp/cpp_helpers.cc:173:6: warning: function 'Base63Char' is not needed and will not be emitted [-Wunneeded-internal-declaration]

char Base63Char(int value) {

     ^

  CXX      google/protobuf/compiler/java/java_enum.lo

1 warning generated.

 

 

google/protobuf/compiler/js/js_generator.cc:97:6: warning: unused function 'StrEndsWith' [-Wunused-function]

bool StrEndsWith(StringPiece sp, StringPiece x) {

     ^

1 warning generated.

 

 

 

In file included from google/protobuf/compiler/csharp/csharp_source_generator_base.cc:39:

./google/protobuf/compiler/csharp/csharp_source_generator_base.h:62:25: warning: private field 'descriptor_' is not used [-Wunused-private-field]

  const FileDescriptor* descriptor_;

                        ^

1 warning generated.
```

### LINKED ISSUE #8612: Warning compiling Protobuf 3.17 with clang++11
On v3.17.0, compiling C++ with clang11 using cmake

Compiler is installed using https://apt.llvm.org/ on Debian 10 AMD64

```
In file included from google/protobuf/compiler/cpp/cpp_field.cc:46:
./google/protobuf/compiler/cpp/cpp_map_field.h:50:8: warning: 'GeneratePrivateMembers' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  void GeneratePrivateMembers(io::Printer* printer) const;
       ^
./google/protobuf/compiler/cpp/cpp_field.h:83:16: note: overridden virtual function is here
  virtual void GeneratePrivateMembers(io::Printer* printer) const = 0;
               ^
In file included from google/protobuf/compiler/cpp/cpp_field.cc:46:
./google/protobuf/compiler/cpp/cpp_map_field.h:51:8: warning: 'GenerateAccessorDeclarations' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  void GenerateAccessorDeclarations(io::Printer* printer) const;
       ^
./google/protobuf/compiler/cpp/cpp_field.h:92:16: note: overridden virtual function is here
  virtual void GenerateAccessorDeclarations(io::Printer* printer) const = 0;
               ^
In file included from google/protobuf/compiler/cpp/cpp_field.cc:46:
./google/protobuf/compiler/cpp/cpp_map_field.h:52:8: warning: 'GenerateInlineAccessorDefinitions' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  void GenerateInlineAccessorDefinitions(io::Printer* printer) const;
       ^
./google/protobuf/compiler/cpp/cpp_field.h:96:16: note: overridden virtual function is here
  virtual void GenerateInlineAccessorDefinitions(
               ^
In file included from google/protobuf/compiler/cpp/cpp_field.cc:46:
./google/protobuf/compiler/cpp/cpp_map_field.h:53:8: warning: 'GenerateClearingCode' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  void GenerateClearingCode(io::Printer* printer) const;
       ^
./google/protobuf/compiler/cpp/cpp_field.h:117:16: note: overridden virtual function is here
  virtual void GenerateClearingCode(io::Printer* printer) const = 0;
               ^
In file included from google/protobuf/compiler/cpp/cpp_field.cc:46:
./google/protobuf/compiler/cpp/cpp_map_field.h:54:8: warning: 'GenerateMergingCode' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  void GenerateMergingCode(io::Printer* printer) const;
       ^
./google/protobuf/compiler/cpp/cpp_field.h:136:16: note: overridden virtual function is here
  virtual void GenerateMergingCode(io::Printer* printer) const = 0;
               ^
In file included from google/protobuf/compiler/cpp/cpp_field.cc:46:
./google/protobuf/compiler/cpp/cpp_map_field.h:55:8: warning: 'GenerateSwappingCode' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  void GenerateSwappingCode(io::Printer* printer) const;
       ^
./google/protobuf/compiler/cpp/cpp_field.h:146:16: note: overridden virtual function is here
  virtual void GenerateSwappingCode(io::Printer* printer) const = 0;
               ^
In file included from google/protobuf/compiler/cpp/cpp_field.cc:46:
./google/protobuf/compiler/cpp/cpp_map_field.h:56:8: warning: 'GenerateConstructorCode' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  void GenerateConstructorCode(io::Printer* printer) const {}
       ^
./google/protobuf/compiler/cpp/cpp_field.h:151:16: note: overridden virtual function is here
  virtual void GenerateConstructorCode(io::Printer* printer) const = 0;
               ^
In file included from google/protobuf/compiler/cpp/cpp_field.cc:46:
./google/protobuf/compiler/cpp/cpp_map_field.h:57:8: warning: 'GenerateCopyConstructorCode' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  void GenerateCopyConstructorCode(io::Printer* printer) const;
       ^
./google/protobuf/compiler/cpp/cpp_field.h:139:16: note: overridden virtual function is here
  virtual void GenerateCopyConstructorCode(io::Printer* printer) const = 0;
               ^
In file included from google/protobuf/compiler/cpp/cpp_field.cc:46:
./google/protobuf/compiler/cpp/cpp_map_field.h:58:8: warning: 'GenerateSerializeWithCachedSizesToArray' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  void GenerateSerializeWithCachedSizesToArray(io::Printer* printer) const;
       ^
./google/protobuf/compiler/cpp/cpp_field.h:177:16: note: overridden virtual function is here
  virtual void GenerateSerializeWithCachedSizesToArray(
               ^
In file included from google/protobuf/compiler/cpp/cpp_field.cc:46:
./google/protobuf/compiler/cpp/cpp_map_field.h:59:8: warning: 'GenerateByteSize' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  void GenerateByteSize(io::Printer* printer) const;
       ^
./google/protobuf/compiler/cpp/cpp_field.h:182:16: note: overridden virtual function is here
  virtual void GenerateByteSize(io::Printer* printer) const = 0;
               ^
In file included from google/protobuf/compiler/cpp/cpp_field.cc:46:
./google/protobuf/compiler/cpp/cpp_map_field.h:60:8: warning: 'GenerateConstinitInitializer' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  void GenerateConstinitInitializer(io::Printer* printer) const;
       ^
./google/protobuf/compiler/cpp/cpp_field.h:172:16: note: overridden virtual function is here
  virtual void GenerateConstinitInitializer(io::Printer* printer) const {}
               ^
11 warnings generated.
In file included from google/protobuf/compiler/cpp/cpp_map_field.cc:31:
./google/protobuf/compiler/cpp/cpp_map_field.h:50:8: warning: 'GeneratePrivateMembers' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  void GeneratePrivateMembers(io::Printer* printer) const;
       ^
./google/protobuf/compiler/cpp/cpp_field.h:83:16: note: overridden virtual function is here
  virtual void GeneratePrivateMembers(io::Printer* printer) const = 0;
               ^
In file included from google/protobuf/compiler/cpp/cpp_map_field.cc:31:
./google/protobuf/compiler/cpp/cpp_map_field.h:51:8: warning: 'GenerateAccessorDeclarations' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  void GenerateAccessorDeclarations(io::Printer* printer) const;
       ^
./google/protobuf/compiler/cpp/cpp_field.h:92:16: note: overridden virtual function is here
  virtual void GenerateAccessorDeclarations(io::Printer* printer) const = 0;
               ^
In file included from google/protobuf/compiler/cpp/cpp_map_field.cc:31:
./google/protobuf/compiler/cpp/cpp_map_field.h:52:8: warning: 'GenerateInlineAccessorDefinitions' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  void GenerateInlineAccessorDefinitions(io::Printer* printer) const;
       ^
./google/protobuf/compiler/cpp/cpp_field.h:96:16: note: overridden virtual function is here
  virtual void GenerateInlineAccessorDefinitions(
               ^
In file included from google/protobuf/compiler/cpp/cpp_map_field.cc:31:
./google/protobuf/compiler/cpp/cpp_map_field.h:53:8: warning: 'GenerateClearingCode' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  void GenerateClearingCode(io::Printer* printer) const;
       ^
./google/protobuf/compiler/cpp/cpp_field.h:117:16: note: overridden virtual function is here
  virtual void GenerateClearingCode(io::Printer* printer) const = 0;
               ^
In file included from google/protobuf/compiler/cpp/cpp_map_field.cc:31:
./google/protobuf/compiler/cpp/cpp_map_field.h:54:8: warning: 'GenerateMergingCode' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  void GenerateMergingCode(io::Printer* printer) const;
       ^
./google/protobuf/compiler/cpp/cpp_field.h:136:16: note: overridden virtual function is here
  virtual void GenerateMergingCode(io::Printer* printer) const = 0;
               ^
In file included from google/protobuf/compiler/cpp/cpp_map_field.cc:31:
./google/protobuf/compiler/cpp/cpp_map_field.h:55:8: warning: 'GenerateSwappingCode' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  void GenerateSwappingCode(io::Printer* printer) const;
       ^
./google/protobuf/compiler/cpp/cpp_field.h:146:16: note: overridden virtual function is here
  virtual void GenerateSwappingCode(io::Printer* printer) const = 0;
               ^
In file included from google/protobuf/compiler/cpp/cpp_map_field.cc:31:
./google/protobuf/compiler/cpp/cpp_map_field.h:56:8: warning: 'GenerateConstructorCode' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  void GenerateConstructorCode(io::Printer* printer) const {}
       ^
./google/protobuf/compiler/cpp/cpp_field.h:151:16: note: overridden virtual function is here
  virtual void GenerateConstructorCode(io::Printer* printer) const = 0;
               ^
In file included from google/protobuf/compiler/cpp/cpp_map_field.cc:31:
./google/protobuf/compiler/cpp/cpp_map_field.h:57:8: warning: 'GenerateCopyConstructorCode' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  void GenerateCopyConstructorCode(io::Printer* printer) const;
       ^
./google/protobuf/compiler/cpp/cpp_field.h:139:16: note: overridden virtual function is here
  virtual void GenerateCopyConstructorCode(io::Printer* printer) const = 0;
               ^
In file included from google/protobuf/compiler/cpp/cpp_map_field.cc:31:
./google/protobuf/compiler/cpp/cpp_map_field.h:58:8: warning: 'GenerateSerializeWithCachedSizesToArray' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  void GenerateSerializeWithCachedSizesToArray(io::Printer* printer) const;
       ^
./google/protobuf/compiler/cpp/cpp_field.h:177:16: note: overridden virtual function is here
  virtual void GenerateSerializeWithCachedSizesToArray(
               ^
In file included from google/protobuf/compiler/cpp/cpp_map_field.cc:31:
./google/protobuf/compiler/cpp/cpp_map_field.h:59:8: warning: 'GenerateByteSize' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  void GenerateByteSize(io::Printer* printer) const;
       ^
./google/protobuf/compiler/cpp/cpp_field.h:182:16: note: overridden virtual function is here
  virtual void GenerateByteSize(io::Printer* printer) const = 0;
               ^
In file included from google/protobuf/compiler/cpp/cpp_map_field.cc:31:
./google/protobuf/compiler/cpp/cpp_map_field.h:60:8: warning: 'GenerateConstinitInitializer' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  void GenerateConstinitInitializer(io::Printer* printer) const;
       ^
./google/protobuf/compiler/cpp/cpp_field.h:172:16: note: overridden virtual function is here
  virtual void GenerateConstinitInitializer(io::Printer* printer) const {}
               ^
google/protobuf/compiler/cpp/cpp_helpers.cc:173:6: warning: function 'Base63Char' is not needed and will not be emitted [-Wunneeded-internal-declaration]
char Base63Char(int value) {
     ^
11 warnings generated.
1 warning generated.
In file included from google/protobuf/compiler/java/java_file.cc:46:
./google/protobuf/compiler/java/java_message.h:105:16: warning: 'Generate' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void Generate(io::Printer* printer);
               ^
./google/protobuf/compiler/java/java_message.h:79:16: note: overridden virtual function is here
  virtual void Generate(io::Printer* printer) = 0;
               ^
./google/protobuf/compiler/java/java_message.h:106:16: warning: 'GenerateInterface' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void GenerateInterface(io::Printer* printer);
               ^
./google/protobuf/compiler/java/java_message.h:83:16: note: overridden virtual function is here
  virtual void GenerateInterface(io::Printer* printer) = 0;
               ^
./google/protobuf/compiler/java/java_message.h:107:16: warning: 'GenerateExtensionRegistrationCode' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void GenerateExtensionRegistrationCode(io::Printer* printer);
               ^
./google/protobuf/compiler/java/java_message.h:87:16: note: overridden virtual function is here
  virtual void GenerateExtensionRegistrationCode(io::Printer* printer) = 0;
               ^
./google/protobuf/compiler/java/java_message.h:108:16: warning: 'GenerateStaticVariables' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void GenerateStaticVariables(io::Printer* printer,
               ^
./google/protobuf/compiler/java/java_message.h:71:16: note: overridden virtual function is here
  virtual void GenerateStaticVariables(io::Printer* printer,
               ^
./google/protobuf/compiler/java/java_message.h:112:15: warning: 'GenerateStaticVariableInitializers' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual int GenerateStaticVariableInitializers(io::Printer* printer);
              ^
./google/protobuf/compiler/java/java_message.h:76:15: note: overridden virtual function is here
  virtual int GenerateStaticVariableInitializers(io::Printer* printer) = 0;
              ^
In file included from google/protobuf/compiler/java/java_message.cc:35:
./google/protobuf/compiler/java/java_message.h:105:16: warning: 'Generate' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void Generate(io::Printer* printer);
               ^
./google/protobuf/compiler/java/java_message.h:79:16: note: overridden virtual function is here
  virtual void Generate(io::Printer* printer) = 0;
               ^
./google/protobuf/compiler/java/java_message.h:106:16: warning: 'GenerateInterface' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void GenerateInterface(io::Printer* printer);
               ^
./google/protobuf/compiler/java/java_message.h:83:16: note: overridden virtual function is here
  virtual void GenerateInterface(io::Printer* printer) = 0;
               ^
./google/protobuf/compiler/java/java_message.h:107:16: warning: 'GenerateExtensionRegistrationCode' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void GenerateExtensionRegistrationCode(io::Printer* printer);
               ^
./google/protobuf/compiler/java/java_message.h:87:16: note: overridden virtual function is here
  virtual void GenerateExtensionRegistrationCode(io::Printer* printer) = 0;
               ^
./google/protobuf/compiler/java/java_message.h:108:16: warning: 'GenerateStaticVariables' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void GenerateStaticVariables(io::Printer* printer,
               ^
./google/protobuf/compiler/java/java_message.h:71:16: note: overridden virtual function is here
  virtual void GenerateStaticVariables(io::Printer* printer,
               ^
./google/protobuf/compiler/java/java_message.h:112:15: warning: 'GenerateStaticVariableInitializers' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual int GenerateStaticVariableInitializers(io::Printer* printer);
              ^
./google/protobuf/compiler/java/java_message.h:76:15: note: overridden virtual function is here
  virtual int GenerateStaticVariableInitializers(io::Printer* printer) = 0;
              ^
In file included from google/protobuf/compiler/java/java_message_lite.cc:35:
In file included from ./google/protobuf/compiler/java/java_message_lite.h:41:
./google/protobuf/compiler/java/java_message.h:105:16: warning: 'Generate' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void Generate(io::Printer* printer);
               ^
./google/protobuf/compiler/java/java_message.h:79:16: note: overridden virtual function is here
  virtual void Generate(io::Printer* printer) = 0;
               ^
./google/protobuf/compiler/java/java_message.h:106:16: warning: 'GenerateInterface' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void GenerateInterface(io::Printer* printer);
               ^
./google/protobuf/compiler/java/java_message.h:83:16: note: overridden virtual function is here
  virtual void GenerateInterface(io::Printer* printer) = 0;
               ^
./google/protobuf/compiler/java/java_message.h:107:16: warning: 'GenerateExtensionRegistrationCode' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void GenerateExtensionRegistrationCode(io::Printer* printer);
               ^
./google/protobuf/compiler/java/java_message.h:87:16: note: overridden virtual function is here
  virtual void GenerateExtensionRegistrationCode(io::Printer* printer) = 0;
               ^
./google/protobuf/compiler/java/java_message.h:108:16: warning: 'GenerateStaticVariables' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void GenerateStaticVariables(io::Printer* printer,
               ^
./google/protobuf/compiler/java/java_message.h:71:16: note: overridden virtual function is here
  virtual void GenerateStaticVariables(io::Printer* printer,
               ^
./google/protobuf/compiler/java/java_message.h:112:15: warning: 'GenerateStaticVariableInitializers' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual int GenerateStaticVariableInitializers(io::Printer* printer);
              ^
./google/protobuf/compiler/java/java_message.h:76:15: note: overridden virtual function is here
  virtual int GenerateStaticVariableInitializers(io::Printer* printer) = 0;
              ^
In file included from google/protobuf/compiler/java/java_message_lite.cc:35:
./google/protobuf/compiler/java/java_message_lite.h:53:16: warning: 'Generate' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void Generate(io::Printer* printer);
               ^
./google/protobuf/compiler/java/java_message.h:79:16: note: overridden virtual function is here
  virtual void Generate(io::Printer* printer) = 0;
               ^
In file included from google/protobuf/compiler/java/java_message_lite.cc:35:
./google/protobuf/compiler/java/java_message_lite.h:54:16: warning: 'GenerateInterface' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void GenerateInterface(io::Printer* printer);
               ^
./google/protobuf/compiler/java/java_message.h:83:16: note: overridden virtual function is here
  virtual void GenerateInterface(io::Printer* printer) = 0;
               ^
In file included from google/protobuf/compiler/java/java_message_lite.cc:35:
./google/protobuf/compiler/java/java_message_lite.h:55:16: warning: 'GenerateExtensionRegistrationCode' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void GenerateExtensionRegistrationCode(io::Printer* printer);
               ^
./google/protobuf/compiler/java/java_message.h:87:16: note: overridden virtual function is here
  virtual void GenerateExtensionRegistrationCode(io::Printer* printer) = 0;
               ^
In file included from google/protobuf/compiler/java/java_message_lite.cc:35:
./google/protobuf/compiler/java/java_message_lite.h:56:16: warning: 'GenerateStaticVariables' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void GenerateStaticVariables(io::Printer* printer,
               ^
./google/protobuf/compiler/java/java_message.h:71:16: note: overridden virtual function is here
  virtual void GenerateStaticVariables(io::Printer* printer,
               ^
In file included from google/protobuf/compiler/java/java_message_lite.cc:35:
./google/protobuf/compiler/java/java_message_lite.h:58:15: warning: 'GenerateStaticVariableInitializers' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual int GenerateStaticVariableInitializers(io::Printer* printer);
              ^
./google/protobuf/compiler/java/java_message.h:76:15: note: overridden virtual function is here
  virtual int GenerateStaticVariableInitializers(io::Printer* printer) = 0;
              ^
In file included from google/protobuf/compiler/java/java_generator_factory.cc:41:
./google/protobuf/compiler/java/java_message.h:105:16: warning: 'Generate' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void Generate(io::Printer* printer);
               ^
./google/protobuf/compiler/java/java_message.h:79:16: note: overridden virtual function is here
  virtual void Generate(io::Printer* printer) = 0;
               ^
./google/protobuf/compiler/java/java_message.h:106:16: warning: 'GenerateInterface' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void GenerateInterface(io::Printer* printer);
               ^
./google/protobuf/compiler/java/java_message.h:83:16: note: overridden virtual function is here
  virtual void GenerateInterface(io::Printer* printer) = 0;
               ^
./google/protobuf/compiler/java/java_message.h:107:16: warning: 'GenerateExtensionRegistrationCode' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void GenerateExtensionRegistrationCode(io::Printer* printer);
               ^
./google/protobuf/compiler/java/java_message.h:87:16: note: overridden virtual function is here
  virtual void GenerateExtensionRegistrationCode(io::Printer* printer) = 0;
               ^
./google/protobuf/compiler/java/java_message.h:108:16: warning: 'GenerateStaticVariables' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void GenerateStaticVariables(io::Printer* printer,
               ^
./google/protobuf/compiler/java/java_message.h:71:16: note: overridden virtual function is here
  virtual void GenerateStaticVariables(io::Printer* printer,
               ^
./google/protobuf/compiler/java/java_message.h:112:15: warning: 'GenerateStaticVariableInitializers' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual int GenerateStaticVariableInitializers(io::Printer* printer);
              ^
./google/protobuf/compiler/java/java_message.h:76:15: note: overridden virtual function is here
  virtual int GenerateStaticVariableInitializers(io::Printer* printer) = 0;
              ^
In file included from google/protobuf/compiler/java/java_generator_factory.cc:42:
./google/protobuf/compiler/java/java_message_lite.h:53:16: warning: 'Generate' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void Generate(io::Printer* printer);
               ^
./google/protobuf/compiler/java/java_message.h:79:16: note: overridden virtual function is here
  virtual void Generate(io::Printer* printer) = 0;
               ^
In file included from google/protobuf/compiler/java/java_generator_factory.cc:42:
./google/protobuf/compiler/java/java_message_lite.h:54:16: warning: 'GenerateInterface' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void GenerateInterface(io::Printer* printer);
               ^
./google/protobuf/compiler/java/java_message.h:83:16: note: overridden virtual function is here
  virtual void GenerateInterface(io::Printer* printer) = 0;
               ^
In file included from google/protobuf/compiler/java/java_generator_factory.cc:42:
./google/protobuf/compiler/java/java_message_lite.h:55:16: warning: 'GenerateExtensionRegistrationCode' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void GenerateExtensionRegistrationCode(io::Printer* printer);
               ^
./google/protobuf/compiler/java/java_message.h:87:16: note: overridden virtual function is here
  virtual void GenerateExtensionRegistrationCode(io::Printer* printer) = 0;
               ^
In file included from google/protobuf/compiler/java/java_generator_factory.cc:42:
./google/protobuf/compiler/java/java_message_lite.h:56:16: warning: 'GenerateStaticVariables' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void GenerateStaticVariables(io::Printer* printer,
               ^
./google/protobuf/compiler/java/java_message.h:71:16: note: overridden virtual function is here
  virtual void GenerateStaticVariables(io::Printer* printer,
               ^
In file included from google/protobuf/compiler/java/java_generator_factory.cc:42:
./google/protobuf/compiler/java/java_message_lite.h:58:15: warning: 'GenerateStaticVariableInitializers' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual int GenerateStaticVariableInitializers(io::Printer* printer);
              ^
./google/protobuf/compiler/java/java_message.h:76:15: note: overridden virtual function is here
  virtual int GenerateStaticVariableInitializers(io::Printer* printer) = 0;
              ^
10 warnings generated.
10 warnings generated.
5 warnings generated.
5 warnings generated.
google/protobuf/compiler/js/js_generator.cc:97:6: warning: unused function 'StrEndsWith' [-Wunused-function]
bool StrEndsWith(StringPiece sp, StringPiece x) {
     ^
1 warning generated.
In file included from google/protobuf/compiler/csharp/csharp_source_generator_base.cc:39:
./google/protobuf/compiler/csharp/csharp_source_generator_base.h:62:25: warning: private field 'descriptor_' is not used [-Wunused-private-field]
  const FileDescriptor* descriptor_;
                        ^
```

### PR DESCRIPTION
**Pull request by Kernald**
This fixes a few kinds of warnings:
 - inconsistent-missing-override when the overriding site is missing the
   override keyword
 - unused-function when a function is neither visible nor used
 - unused-private-field when a private field exists but is never used
 - sign-compare when unsigned ints are compared to signed ints. Not all
   of those have been addressed, but this warning isn't enabled by
   default.

This fixes #8580, fixes #8612.

### CODE REVIEW

File: src/google/protobuf/compiler/importer.cc [hunk 1]
```diff
@@ -290,7 +290,7 @@ static std::string CanonicalizePath(std::string path) {
   std::vector<std::string> canonical_parts;
   std::vector<std::string> parts = Split(
       path, "/", true);  // Note:  Removes empty parts.
-  for (int i = 0; i < parts.size(); i++) {
+  for (unsigned int i = 0; i < parts.size(); i++) {
```
Comment (acozzette) [inline src/google/protobuf/compiler/importer.cc:293]: Our style guide is very particular about [integer types](https://google.github.io/styleguide/cppguide.html#Integer_Types), and doesn't allow any of the plain builtin C integer types except for plain `int` (so `unsigned` isn't allowed). I think the best solution for this kind of warning is to change these loops to be range-based for loops.

Comment (fowles) [reply src/google/protobuf/compiler/importer.cc:293]: size_t is allowed, although ranged based for loops are usually nicer

Comment (Kernald) [reply src/google/protobuf/compiler/importer.cc:293]: I fixed some of them with ranges, and reverted some of them (I haven't written any C++ in ages, I went for the easy way) - those warnings are not enabled by default when building with -Werror anyway, so it's not as blocking as the others.

File: src/google/protobuf/compiler/importer.cc [hunk 2]
```diff
@@ -290,11 +290,11 @@ static std::string CanonicalizePath(std::string path) {
   std::vector<std::string> canonical_parts;
   std::vector<std::string> parts = Split(
       path, "/", true);  // Note:  Removes empty parts.
-  for (int i = 0; i < parts.size(); i++) {
-    if (parts[i] == ".") {
+  for (auto && part : parts) {
```
Comment (acozzette) [inline src/google/protobuf/compiler/importer.cc:293]: I think most (or all) of these don't need to be rvalue references since they're not being modified, so for example in this case it should be `const std::string&` or `const auto&` instead of `auto &&`.

File: src/google/protobuf/stubs/stringprintf.cc [hunk 3]
```diff
@@ -150,10 +150,10 @@ std::string StringPrintfVector(const char* format,
   // or displaying random chunks of memory to users.
 
   const char* cstr[kStringPrintfVectorMaxArgs];
-  for (int i = 0; i < v.size(); ++i) {
+  for (unsigned int i = 0; i < v.size(); ++i) {
```
Comment (acozzette) [inline src/google/protobuf/stubs/stringprintf.cc:153]: This file has a couple more cases of `unsigned`.

File: src/google/protobuf/util/field_mask_util.cc [hunk 4]
```diff
@@ -417,14 +416,14 @@ void FieldMaskTree::IntersectPath(const std::string& path, FieldMaskTree* out) {
...
-  for (int i = 0; i < parts.size(); ++i) {
+  for (auto && part : parts) {
     if (node->children.empty()) {
       if (node != &root_) {
         out->AddPath(path);
       }
       return;
     }
-    const std::string& node_name = parts[i];
+    const std::string& node_name = part;
```
Comment (acozzette) [inline src/google/protobuf/util/field_mask_util.cc:426]: I would just call the loop variable `node_name` so that this line becomes unnecessary.

**Review by acozzette — CHANGES_REQUESTED** [review]
Thanks for the cleanup! Looks good to me except for a few more small comments I made.

File: src/google/protobuf/compiler/importer.cc (hunk 2 above)
Comment (Kernald) [reply src/google/protobuf/compiler/importer.cc]: Thanks, done

File: src/google/protobuf/stubs/stringprintf.cc (hunk 3 above)
Comment (Kernald) [reply src/google/protobuf/stubs/stringprintf.cc]: Woops, done

File: src/google/protobuf/util/field_mask_util.cc (hunk 4 above)
Comment (Kernald) [reply src/google/protobuf/util/field_mask_util.cc]: Done as well.

File: src/google/protobuf/util/field_mask_util.cc [hunk 5]
```diff
@@ -52,17 +52,17 @@ std::string FieldMaskUtil::ToString(const FieldMask& mask) {
...
+    out->add_paths(path);
   }
 }
 
 bool FieldMaskUtil::SnakeCaseToCamelCase(StringPiece input,
                                          std::string* output) {
   output->clear();
   bool after_underscore = false;
-  for (int i = 0; i < input.size(); ++i) {
+  for (unsigned int i = 0; i < input.size(); ++i) {
```
Comment (acozzette) [inline src/google/protobuf/util/field_mask_util.cc:65]: One more `unsigned` here, I think this one could be a range-based for loop.

File: src/google/protobuf/util/field_mask_util.cc [hunk 6]
```diff
@@ -332,14 +331,14 @@ void FieldMaskTree::AddPath(const std::string& path) {
...
-  for (int i = 0; i < parts.size(); ++i) {
+  for (const std::string& part : parts) {
     if (!new_branch && node != &root_ && node->children.empty()) {
       // Path matches an existing leaf node. This means the path is already
       // covered by this tree (for example, adding "foo.bar.baz" to a tree
       // which already contains "foo.bar").
       return;
     }
-    const std::string& node_name = parts[i];
+    const std::string& node_name = part;
```
Comment (acozzette) [inline src/google/protobuf/util/field_mask_util.cc:341]: I think this loop could do the same thing as the one below and just name the loop variable `node_name` so that this line can be deleted.

**Review by acozzette — CHANGES_REQUESTED** [review]
Sorry but I added just two more things I might missed before, otherwise looks great.

File: src/google/protobuf/util/field_mask_util.cc (hunk 5 above)
Comment (Kernald) [reply src/google/protobuf/util/field_mask_util.cc]: Done

File: src/google/protobuf/util/field_mask_util.cc (hunk 6 above)
Comment (Kernald) [reply src/google/protobuf/util/field_mask_util.cc]: Done

**Comment by Kernald** [comment]
I just addressed the last comments and rebased on `master`.
