### PR TITLE
Fix -Wunused-parameter in map<string, int> fields (fixes #8494)

### LINKED ISSUE #8494: Generated map<string, string> code might trigger unused parameter warning
**What version of protobuf and what language are you using?**
Version: master
Language: C++

**What operating system (Linux, Windows, ...) and version?** Linux, any will do

**What runtime / compiler are you using (e.g., python version or gcc version)**
clang or gcc, with -Wunused-parameter switch enabled

**What did you do?**
1. Use map<string, string> field in a message
2. Use syntax="proto2"; (default behavior)
3. Don't use optimize_for="lite_runtime"; (default behavior)
3. Get
```
error: unused parameter 'p' [-Werror,-Wunused-parameter]
      static void Check(ConstPtr p) {
```
in utf8 key / value validation.

**Anything else we should know about your project / environment**

The issue is triggered by incorrect check. At the time key / value validation method is invoked if either key or value is string.
However, the Utf8CheckMode must be taken into account and check generation / invokation should be omitted.

The fix will result in a number of pull requests. I am goind to attach them all to this issue.

### PR DESCRIPTION
**Pull request by georgthegreat**
This is a clumsy fix for #8494.
MWE is as follows:

```
syntax = "proto2";
optimize_for = "lite_runtime";
message M {
   map<string, int> field = 1;
}
```

During code generation, protoc will check for key / value types (corresponds to string_key / string_value variables all around).
If Utf8 validation will be disabled due to evaluation of `GetUtf8CheckMode()` to `kNone`, the `Check()` method will be generated as follows:
```
static void Check(ConstPtr p) {
}
```

This will trigger `-Wunused-parameter`.

### CODE REVIEW

File: src/google/protobuf/compiler/cpp/cpp_map_field.cc [hunk 1]
```diff
@@ -229,7 +229,10 @@ void MapFieldGenerator::GenerateSerializeWithCachedSizesToArray(
   if (utf8_check) {
     format(
         "struct Utf8Check {\n"
-        "  static void Check(ConstPtr p) {\n");
+        "  static void Check(ConstPtr p) {\n"
+		// p may be unused when GetUtf8CheckMode evaluates to kNone,
```
Comment (acozzette) [inline src/google/protobuf/compiler/cpp/cpp_map_field.cc:233]: Looks good but would you mind fixing the indentation? (I think your editor must have inserted tabs whereas we always use spaces.)

Comment (georgthegreat) [reply src/google/protobuf/compiler/cpp/cpp_map_field.cc:233]: Should be fixed now.

Btw, have you considered providing [.editorconfig](https://editorconfig.org/) with the basic indentation rules?

Comment (acozzette) [reply src/google/protobuf/compiler/cpp/cpp_map_field.cc:233]: The formatting doesn't look quite right yet, maybe you just need to do a git push?

I hadn't heard of editorconfig before. I wonder if someone has already written a config to match the Google C++ style guide.

Comment (georgthegreat) [reply src/google/protobuf/compiler/cpp/cpp_map_field.cc]: Sorry, something went wrong with git pushing.
Should be fixed now.

**Comment by georgthegreat** [comment]
@acozzette, could you, please, clarify the release timeline of protobuf=3.16 and protobuf=3.17 (as I see, 3.17.0-rc1 has just appeared in tags).

I have most of the patches submitted as PRs applied locally, and I am waiting for release to remove them. As I see, this PR is not included into 3.16.0-rc2 though it landed in the master some time ago.

Does protobuf follow the trunk based development practice?

**Comment by acozzette** [comment]
We ordinarily do what one would call trunk-based development, but this is just an unusual case where we need to do two releases in quick succession. 3.16 is going to be a long-term support release for Java and will get fixes for at least a year, but we have other changes we want to release in 3.17 which we don't want to commit to supporting for that long. 3.17 includes everything merged to master up to this morning and I expect to release it either by tomorrow or early next week.

**Comment by georgthegreat** [comment]
Thanks for the clarification!
I will wait to 3.17 then.
