### PR TITLE
fix(ruby): Fix various exceptions in Ruby on 64-bit Windows

### LINKED ISSUE #8554: [Ruby] Exception inspecting a message on Windows (3.15 regression)
/attn: @haberman

**What version of protobuf and what language are you using?**
Version: 3.15.8
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
Windows Server 2019 (10.0.17763), via the "windows-latest" platform on GitHub Actions.

**What runtime / compiler are you using (e.g., python version or gcc version)**
n/a (using the binary gem release)

**What did you do?**

```ruby
require "google/protobuf"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("windoze.proto", :syntax => :proto3) do
    add_message "windoze.SimpleTest" do
      # Note: No fields necessary
    end
  end
end
module Windoze
  SimpleTest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("windoze.SimpleTest").msgclass
end

message = Windoze::SimpleTest.new
puts message.inspect
```

**What did you expect to see**

I expect a string representation of an empty message to be displayed.

**What did you see instead?**

A `TypeError` is raised with the following message: ```in `inspect': wrong argument type nil (expected Google::Protobuf::DescriptorPool)```.

The stack trace identifies the final line in the provided Ruby code (`puts message.inspect`) but no further information is given. (I believe the `inspect` method is [implemented in C](https://github.com/protocolbuffers/protobuf/blob/38e1b592581983548eb8012e45a3a1da64b6504f/ruby/ext/google/protobuf_c/message.c#L748).)

**Anything else we should know about your project / environment**

* This appears to be a 3.15 regression. It does not reproduce on 3.14, but does reproduce on various patchlevels of 3.15. (I tried 3.15.8, 3.15.6, and 3.15.2.)
* This appears to be Windows-specific. I can get it to reproduce on a Windows machine (via GitHub Actions), but not on MacOS or Linux.
* I can reproduce it by installing the `x64-mingw32` build of the gem, and by forcing the platform to `ruby` and building the gem from source on install.
* The error appears regardless of whether there are fields present in the proto description or not.
* There are different ways of reproducing the error. The sample code above is the simplest, but I'm also able to reproduce it under certain circumstances when fetching fields in a nested message structure. I can provide additional repro examples if needed.

### PR DESCRIPTION
**Pull request by dazuma**
Activates the secondary ObjectCache map on this platform, to prevent weak keys from being garbage collected. This happened on 64-bit Windows because pointers don't necessarily fit in a Fixnum, and were being represented as GC-able Bignums on that platform.

Fixes #8554

/attn @haberman

### CODE REVIEW

File: ruby/ext/google/protobuf_c/protobuf.c [hunk 1]
```diff
@@ -238,8 +238,16 @@ void Arena_register(VALUE module) {
...
+//
+// We also need the secondary Hash if sizeof(long) < sizeof(VALUE), because this
+// means it may not be possible to fit a pointer into a Fixnum. Keys are
+// pointers, and if they fit into a Fixnum, Ruby doesn't collect them, but if
+// they overflow and require allocating a Bignum, they could get collected
+// prematurely, thus removing the cache entry. This happens on 64-bit Windows,
+// on which pointers are 64 bits but longs are 32 bits. In this case, we enable
+// the secondary Hash to hold the keys and prevent them from being collected.
+
+#if RUBY_API_VERSION_CODE >= 20700 && SIZEOF_LONG >= SIZEOF_VALUE
```
Comment (haberman) [inline ruby/ext/google/protobuf_c/protobuf.c:250]: Our direct concern is that an `intptr_t` divided by 4 can fit in a `fixnum`. This seems like a slightly roundabout way of checking that.

Perhaps we could do:

```
#if RUBY_FIXNUM_MAX >= (INTPTR_MAX / 4)
```

I also notice there is some extraneous code left in the function below. And we should change to use `INT2FIX()` so we get a loud error when our check is incorrect. How about we do this:

```c
static VALUE ObjectCache_GetKey(const void* key, bool create) {
  intptr_t key_int = (intptr_t)key;
  PBRUBY_ASSERT((key_int & 3) == 0);
  VALUE ret = INT2FIX(key_int >> 2);
#if USE_SECONDARY_MAP
  ret = SecondaryMap_Get(ret, create);
#endif
  return ret;
}
```

Comment (dazuma) [reply ruby/ext/google/protobuf_c/protobuf.c:250]: Regarding the preprocessor check: I was actually doing this based on [value.h](https://github.com/ruby/ruby/blob/b85fd1d690b65efaa126cf9c24da73f31eee7a4e/include/ruby/internal/value.h) which doesn't depend on `intptr_t` (and `INTPTR_MAX`) being defined, but conditionally defines `VALUE` (and its size) differently depending on what's available. Ruby has already defined `VALUE` as a proxy for a pointer, and `SIZEOF_VALUE` as the size thereof, and I think we should use the abstraction it provides. In fact, for better compatibility, I might argue that we also should avoid depending on `intptr_t`, and use `VALUE` instead:

```ruby
static VALUE ObjectCache_GetKey(const void* key, bool create) {
  VALUE key_val = (VALUE)key;
  PBRUBY_ASSERT((key_val & 3) == 0);
  VALUE ret = LL2NUM(key_val >> 2);
#if USE_SECONDARY_MAP
  ret = SecondaryMap_Get(ret, create);
#endif
  return ret;
}
```

Regarding the two extraneous lines, I'll remove them.

Regarding using `INT2FIX`, I don't think we can do that. The whole point is that on Win64, it may _not_ be a Fixnum, and we have to reinstate the secondary Hash to compensate.

Pushed an update with the above suggestions.

Comment (haberman) [reply ruby/ext/google/protobuf_c/protobuf.c:250]: You are right re: `INT2FIX`. Using `VALUE` seems reasonable, as it is typedef'd to `uintptr_t`.

This is the check I should have suggested:

```
static VALUE ObjectCache_GetKey(const void* key, bool create) {
  VALUE key_val = (VALUE)key;
  PBRUBY_ASSERT((key_val & 3) == 0);
  VALUE ret = LL2NUM(key_val >> 2);
#if USE_SECONDARY_MAP
  ret = SecondaryMap_Get(ret, create);
#endif
  if (!RB_FIXNUM_P(ret)) rb_raise(rb_eRuntimeError, "Key must be fixed!");
  return ret;
}
```

In other words, after the secondary map step, the key must be a fixnum for the main object cache to be safe.

Comment (dazuma) [reply ruby/ext/google/protobuf_c/protobuf.c:250]: I actually don't think we can do that either. In the case where the secondary map is in use, the key is an [arbitrary object](https://github.com/protocolbuffers/protobuf/blob/5df4c2ec9426b06dfe8a019ddcf1509b8816cebe/ruby/ext/google/protobuf_c/protobuf.c#L329), not a Fixnum. (We know it's not going to get collected because the secondary map is holding on to it.)

Incidentally, that `rb_eval_string("Object.new")` should also be changed to something less heavyweight (i.e. not involving parsing Ruby code) since it's part of the inner loop, called every time the cache is accessed. I changed it.

Comment (haberman) [reply ruby/ext/google/protobuf_c/protobuf.c:250]: Ah, you're absolutely right. Thanks for the changes.
