### PR TITLE
Php 7.3 fix

### LINKED ISSUE #4933: Broken with PHP 7.3.0alpha4
Build ok since pr #4898 is merged but extension dosn't load (since 7.3.0alpha4, was OK with alpha3)

`$ php --no-php-ini --define extension=modules/protobuf.so --modules | grep protobuf`

Output is empty. No error message.

P.S. as I can't sign your CLA, I don't plan to work on this issue to propose a fix, so, do it yourself.

### PR DESCRIPTION
**Pull request by TeBoring**
#4933

### CODE REVIEW

**Comment by TeBoring** [comment]
@haon4 could you help review the docker and continuous test changing.

**Comment by TeBoring** [comment]
@michaelbausor could you help review the php change?

File: .gitignore [hunk 1]
```diff
@@ -145,7 +145,9 @@ php/ext/google/protobuf/Makefile.objects
 php/ext/google/protobuf/acinclude.m4
 php/ext/google/protobuf/build/
 php/ext/google/protobuf/config.h
+php/ext/google/protobuf/config.h.in~
```
Comment (michaelbausor) [inline .gitignore]: The trailing `~` looks odd - is that meant to be there?

File: php/tests/encode_decode_test.php [hunk 2]
```diff
@@ -31,6 +31,7 @@ public function testDecodeJsonSimple()
     {
         $m = new TestMessage();
         $m->mergeFromJsonString("{\"optionalInt32\":1}");
+        $this->assertTrue(true);
```
Comment (michaelbausor) [inline php/tests/encode_decode_test.php]: Why is this necessary? What about asserting that `$m->getOptionalInt32()` equals `1`?

File: tests.sh [hunk 3]
```diff
@@ -349,7 +340,7 @@ build_php5.5() {
 
 build_php5.5_c() {
   use_php 5.5
-  wget https://phar.phpunit.de/phpunit-4.8.0.phar -O /usr/bin/phpunit
+  ls /usr/local/php-5.5/bin
```
Comment (michaelbausor) [inline tests.sh]: Do we want to keep the `ls` call, or is this for debugging?

File: .gitignore (hunk 1 above)
Comment (haon4) [reply .gitignore]: +1. Is this change expected?

File: kokoro/linux/32-bit/build.sh [hunk 4]
```diff
@@ -10,8 +10,9 @@
...
 cd $(dirname $0)/../../..
 
-export DOCKERFILE_DIR=kokoro/linux/32-bit
+export DOCKERHUB_ORGANIZATION=protobuftesting
+export DOCKERFILE_DIR=kokoro/linux/dockerfile/test/php_32bit
 export DOCKER_RUN_SCRIPT=kokoro/linux/pull_request_in_docker.sh
 export OUTPUT_DIR=testoutput
 export TEST_SET="php_all_32"
-./kokoro/linux/build_and_run_docker.sh
+./kokoro/linux/build_and_run_docker2.sh
```
Comment (haon4) [inline kokoro/linux/32-bit/build.sh]: Is this necessary? How about we just update build_and_run_docker to set a default DOCKERHUB_ORGANIZATION only if it is not already set? Then we don't need two almost identical script.

File: kokoro/linux/dockerfile/test/php_32bit/Dockerfile [hunk 5]
```diff
@@ -0,0 +1,224 @@
...
+  make \
+  parallel \
+  time \
+  wget \
+  && apt-get clean
+
+# Install php dependencies
+RUN apt-get clean && apt-get update && apt-get install -y --force-yes \
+  bison \
+  php5 \
```
Comment (haon4) [inline kokoro/linux/dockerfile/test/php_32bit/Dockerfile]: should this be installed here if we can going to install php manually below?

File: kokoro/linux/dockerfile/test/php_32bit/Dockerfile [hunk 6]
```diff
@@ -0,0 +1,224 @@
+FROM 32bit/debian:jessie
```
Comment (haon4) [inline kokoro/linux/dockerfile/test/php_32bit/Dockerfile]: is it better to have all PHP versions setup in one file? or would it be preferable split them up into separate Dockerfiles?

File: .gitignore (hunk 1 above)
Comment (TeBoring) [reply .gitignore]: Yes, I don't know why but compiling php7.3 code always have that.

File: kokoro/linux/dockerfile/test/php_32bit/Dockerfile (hunk 5 above)
Comment (TeBoring) [reply kokoro/linux/dockerfile/test/php_32bit/Dockerfile]: We have to install a php first in order to install composer later.

File: kokoro/linux/dockerfile/test/php_32bit/Dockerfile (hunk 6 above)
Comment (TeBoring) [reply kokoro/linux/dockerfile/test/php_32bit/Dockerfile]: As discussed on meeting, for php, we can share docker image as much as possible.
However, it's not possible to share docker image between 64 and 32 bit tests.

File: php/tests/encode_decode_test.php (hunk 2 above)
Comment (TeBoring) [reply php/tests/encode_decode_test.php]: Change this to assert equals 1.
For the other assertTrue, higher version of phpunit want to have at least one assertion. Otherwise, it will throw warnings.

File: tests.sh (hunk 3 above)
Comment (TeBoring) [reply tests.sh]: Removed.

**Comment by kibertoad** [comment]
I assume this is coming in 3.6.2?
