### PR TITLE
fix(ruby): Fix crash when calculating Message hash values on 64-bit Windows

### LINKED ISSUE #8564: [Ruby] Message#hash crashes with a C assertion on Windows
**What version of protobuf and what language are you using?**
Version: 3.15.8
Language: Ruby 2.7.3, 3.0.1

**What operating system (Linux, Windows, ...) and version?**
Windows Server 2019 (10.0.17763), via the "windows-latest" platform on GitHub Actions.

**What runtime / compiler are you using (e.g., python version or gcc version)**
n/a (using the binary gem release)

**What did you do?**

```ruby
require "google/protobuf"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("windoze.proto", :syntax => :proto3) do
    add_message "windoze.SimpleTest" do
      # Note: No fields necessary
    end
  end
end
module Windoze
  SimpleTest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("windoze.SimpleTest").msgclass
end

message = Windoze::SimpleTest.new
puts message.hash
```

**What did you expect to see**
An integer hash value displayed

**What did you see instead?**
The Ruby VM terminates with the following assertion coming from C code:
```
[BUG] Unnormalized Fixnum value 0xbb5cc1f7724449a5
```

**Anything else we should know about your project / environment**

I found this while investigating #8554. The assertion is coming from [here](https://github.com/ruby/ruby/blob/b85fd1d690b65efaa126cf9c24da73f31eee7a4e/numeric.c#L3545) and seems to happen if the value claims to be a Fixnum but doesn't fall within the range of the `long` type. Thus, it could trigger on 64-bit Windows where longs are 32 bits, if the Fixnum is set from a 64-bit value. This is indeed the case in `Message_hash`, which takes a [64-bit integer from wyhash](https://github.com/protocolbuffers/protobuf/blob/436bd7880e458532901c58f4d9d1ea23fa7edd52/ruby/ext/google/protobuf_c/message.c#L720), and [crams it directly into `INT2FIX`](https://github.com/protocolbuffers/protobuf/blob/436bd7880e458532901c58f4d9d1ea23fa7edd52/ruby/ext/google/protobuf_c/message.c#L737).

This does not seem to trigger on Linux or MacOS, which is unsurprising because `long` is 64-bit on those platforms.

### PR DESCRIPTION
**Pull request by dazuma**
Fixes #8564

On 64-bit Windows, it is unsafe to try to create a Fixnum from a 64-bit integer, because longs can hold only 32 bits. The code change below:
* Downcasts the original unsigned 64-bit hash to a signed long (which may be either 64 bits or 32 bits depending on the platform).
* Checks the value to see if it's in the half of the range of long that corresponds to a valid Fixnum, and moves it into range if not.
* Only then does it pass the result into `INT2FIX`.

/attn @haberman

### CODE REVIEW

**Comment by dazuma** [comment]
Updated with a uniform mapping.

File: ruby/ext/google/protobuf_c/message.c [hunk 1]
```diff
@@ -734,7 +734,16 @@ uint64_t Message_Hash(const upb_msg* msg, const upb_msgdef* m, uint64_t seed) {
  */
 static VALUE Message_hash(VALUE _self) {
   Message* self = ruby_to_Message(_self);
-  return INT2FIX(Message_Hash(self->msg, self->msgdef, 0));
+  uint64_t hash_value = Message_Hash(self->msg, self->msgdef, 0);
+  // Fixnum is restricted to signed long, so downcast if necessary.
+  long long_value = (long)hash_value;
```
Comment (haberman) [inline ruby/ext/google/protobuf_c/message.c:739]: What about:

```
  // RUBY_FIXNUM_MAX should be one less than a power of 2.
  assert(RUBY_FIXNUM_MAX & (RUBY_FIXNUM_MAX + 1) == 0);  
  return INT2FIX(hash_value & RUBY_FIXNUM_MAX);
```

Comment (dazuma) [reply ruby/ext/google/protobuf_c/message.c]: Yeah, that works. It restricts hash values to positive, but I think 32-bit hashes are always positive for most Ruby objects anyway.

**Comment by dazuma** [comment]
Looking at the failed Ruby 2.4 test, I think we can address it by pinning the `irb` gem to `~> 1.1` on Ruby 2.4 (since newer versions of irb depend on reline, which requires Ruby 2.5+).

File: ruby/ext/google/protobuf_c/message.c [hunk 2]
```diff
@@ -734,7 +734,10 @@ uint64_t Message_Hash(const upb_msg* msg, const upb_msgdef* m, uint64_t seed) {
  */
 static VALUE Message_hash(VALUE _self) {
   Message* self = ruby_to_Message(_self);
-  return INT2FIX(Message_Hash(self->msg, self->msgdef, 0));
+  uint64_t hash_value = Message_Hash(self->msg, self->msgdef, 0);
+  // RUBY_FIXNUM_MAX should be one less than a power of 2.
+  assert(RUBY_FIXNUM_MAX & (RUBY_FIXNUM_MAX + 1) == 0);
```
Comment (haberman) [inline ruby/ext/google/protobuf_c/message.c:739]: Sorry, this is my bad, I always forget that the precedence of `&` is low. It should be:

```
assert((RUBY_FIXNUM_MAX & (RUBY_FIXNUM_MAX + 1)) == 0);
```

**Comment by haberman** [comment]
> I think we can address it by pinning the irb gem to ~> 1.1 on Ruby 2.4 (since newer versions of irb depend on reline, which requires Ruby 2.5+).

SGTM.

File: ruby/ext/google/protobuf_c/message.c (hunk 2 above)
Comment (dazuma) [reply ruby/ext/google/protobuf_c/message.c]: Whoops, I forgot that too. Fixed.

**Comment by dazuma** [comment]
> Looking at the failed Ruby 2.4 test, I think we can address it by pinning the irb gem to ~> 1.1 on Ruby 2.4 (since newer versions of irb depend on reline, which requires Ruby 2.5+).

I added this change to the Gemfile. We can try rerunning the tests to make sure it works.

**Review by haberman — APPROVED** [review]
